controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController


# panda_arm_controller:
#   ros__parameters:
#     joints:
#       - panda_joint1
#       - panda_joint2
#       - panda_joint3
#       - panda_joint4
#       - panda_joint5
#       - panda_joint6
#       - panda_joint7
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_partial_joints_goal: true
#
#     # trajectory_execution:
#     #   max_allowed_time: 400
#     #   allowed_start_tolerance: 0.1
#     #   allowed_execution_duration_scaling: 0.0
#     #   wait_for_state_timeout: 5.0
#
# hand_controller:
#   ros__parameters:
#     joints:
#       - panda_finger_joint1
#       # - panda_finger_joint2
#     # command_interfaces:
#     #   - position
#     # state_interfaces:
#     #   - position
#     # allow_partial_joints_goal: true
#     #
#     # trajectory_execution:
#     #   max_allowed_time: 400
#     #   allowed_start_tolerance: 0.1
#     #   allowed_execution_duration_scaling: 0.0
#     #r  wait_for_state_timeout: 5.0



# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz
#     use_sim_time: true

    # panda_arm_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #
    #
    # hand_controller:
    #   type: position_controllers/GripperActionController
    #
    #
    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joint: panda_finger_joint1
